export const NEW_PAGE_INIT = 'NEW_PAGE_INIT';
export const FETCH_JOB_PROFILE_REQUEST = 'FETCH_JOB_PROFILE_REQUEST';
export const FETCH_JOB_PROFILE_SUCCESS = 'FETCH_JOB_PROFILE_SUCCESS';
export const FETCH_JOB_PROFILE_FAIL = 'FETCH_JOB_PROFILE_FAIL';
export const UNAUTH = 'UNAUTH'